export type ThemeType = 'light' | 'dark' | 'orange' | 'green' | 'blue' | 'purple' | 'khaki' | 'pink';

export const PASTEL_THEMES: Record<ThemeType, {
    bg: string;
    bgSecondary: string;
    border: string;
    text: string;
    textSecondary: string;
    accent: string;
    cardBg: string;
    hoverBg: string; // For light interactions
    primary: string; // Main action buttons
    primaryHover: string;
    ring: string; // Focus rings
    emoji: string;
    nextEmoji: string;
    folderFill: string;
    folderStroke: string;
    folderHoverFill: string;
    folderHoverStroke: string;
}> = {
    light: {
        bg: 'bg-gray-50',
        bgSecondary: 'bg-white',
        border: 'border-gray-200',
        text: 'text-gray-900',
        textSecondary: 'text-gray-500',
        accent: 'text-blue-600',
        cardBg: 'bg-white',
        hoverBg: 'hover:bg-gray-100',
        primary: 'bg-blue-600',
        primaryHover: 'hover:bg-blue-700',
        ring: 'ring-blue-500',
        emoji: '☀️',
        nextEmoji: '🌙',
        folderFill: 'fill-white',
        folderStroke: 'stroke-gray-200',
        folderHoverFill: 'group-hover:fill-gray-50',
        folderHoverStroke: 'group-hover:stroke-gray-300',
    },
    dark: {
        bg: 'bg-[#000000]',
        bgSecondary: 'bg-[#1d1d1f]',
        border: 'border-[#3d3d3f]',
        text: 'text-white',
        textSecondary: 'text-[#86868b]',
        accent: 'text-[#0a84ff]',
        cardBg: 'bg-[#1d1d1f]',
        hoverBg: 'hover:bg-white/5',
        primary: 'bg-[#0a84ff]',
        primaryHover: 'hover:bg-[#0071e3]',
        ring: 'ring-[#0a84ff]',
        emoji: '🌙',
        nextEmoji: '🍊',
        folderFill: 'fill-[#1c1c1e]',
        folderStroke: 'stroke-[#3a3a3c]/50',
        folderHoverFill: 'group-hover:fill-[#2c2c2e]',
        folderHoverStroke: 'group-hover:stroke-[#48484a]',
    },
    orange: {
        bg: 'bg-stone-50', // Neutral contrast
        bgSecondary: 'bg-orange-100/30',
        border: 'border-orange-200',
        text: 'text-orange-950',
        textSecondary: 'text-orange-700/80',
        accent: 'text-orange-700',
        cardBg: 'bg-orange-50/50', // Tinted container
        hoverBg: 'hover:bg-orange-100',
        primary: 'bg-orange-600',
        primaryHover: 'hover:bg-orange-700',
        ring: 'ring-orange-500',
        emoji: '🍊',
        nextEmoji: '🥒',
        folderFill: 'fill-orange-50',
        folderStroke: 'stroke-orange-200',
        folderHoverFill: 'group-hover:fill-orange-100',
        folderHoverStroke: 'group-hover:stroke-orange-300',
    },
    green: {
        bg: 'bg-stone-50',
        bgSecondary: 'bg-emerald-100/30',
        border: 'border-emerald-200',
        text: 'text-emerald-950',
        textSecondary: 'text-emerald-700/80',
        accent: 'text-emerald-700',
        cardBg: 'bg-emerald-50/50',
        hoverBg: 'hover:bg-emerald-100',
        primary: 'bg-emerald-600',
        primaryHover: 'hover:bg-emerald-700',
        ring: 'ring-emerald-500',
        emoji: '🥒',
        nextEmoji: '🧊',
        folderFill: 'fill-emerald-50',
        folderStroke: 'stroke-emerald-200',
        folderHoverFill: 'group-hover:fill-emerald-100',
        folderHoverStroke: 'group-hover:stroke-emerald-300',
    },
    blue: {
        bg: 'bg-slate-50',
        bgSecondary: 'bg-sky-100/30',
        border: 'border-sky-200',
        text: 'text-sky-950',
        textSecondary: 'text-sky-700/80',
        accent: 'text-sky-700',
        cardBg: 'bg-sky-50/50',
        hoverBg: 'hover:bg-sky-100',
        primary: 'bg-sky-600',
        primaryHover: 'hover:bg-sky-700',
        ring: 'ring-sky-500',
        emoji: '🧊',
        nextEmoji: '🍇',
        folderFill: 'fill-sky-50',
        folderStroke: 'stroke-sky-200',
        folderHoverFill: 'group-hover:fill-sky-100',
        folderHoverStroke: 'group-hover:stroke-sky-300',
    },
    purple: {
        bg: 'bg-slate-50',
        bgSecondary: 'bg-violet-100/30',
        border: 'border-violet-200',
        text: 'text-violet-950',
        textSecondary: 'text-violet-700/80',
        accent: 'text-violet-700',
        cardBg: 'bg-violet-50/50',
        hoverBg: 'hover:bg-violet-100',
        primary: 'bg-violet-600',
        primaryHover: 'hover:bg-violet-700',
        ring: 'ring-violet-500',
        emoji: '🍇',
        nextEmoji: '🥜',
        folderFill: 'fill-violet-50',
        folderStroke: 'stroke-violet-200',
        folderHoverFill: 'group-hover:fill-violet-100',
        folderHoverStroke: 'group-hover:stroke-violet-300',
    },
    khaki: {
        bg: 'bg-stone-50',
        bgSecondary: 'bg-amber-100/30',
        border: 'border-amber-200',
        text: 'text-amber-950',
        textSecondary: 'text-amber-700/80',
        accent: 'text-amber-700',
        cardBg: 'bg-amber-50/50',
        hoverBg: 'hover:bg-amber-100',
        primary: 'bg-amber-600',
        primaryHover: 'hover:bg-amber-700',
        ring: 'ring-amber-500',
        emoji: '🥜',
        nextEmoji: '🌸',
        folderFill: 'fill-amber-50',
        folderStroke: 'stroke-amber-200',
        folderHoverFill: 'group-hover:fill-amber-100',
        folderHoverStroke: 'group-hover:stroke-amber-300',
    },
    pink: {
        bg: 'bg-stone-50',
        bgSecondary: 'bg-pink-100/30',
        border: 'border-pink-200',
        text: 'text-pink-950',
        textSecondary: 'text-pink-700/80',
        accent: 'text-pink-700',
        cardBg: 'bg-pink-50/50', // Tinted
        hoverBg: 'hover:bg-pink-100',
        primary: 'bg-pink-600',
        primaryHover: 'hover:bg-pink-700',
        ring: 'ring-pink-500',
        emoji: '🌸',
        nextEmoji: '☀️',
        folderFill: 'fill-pink-50',
        folderStroke: 'stroke-pink-200',
        folderHoverFill: 'group-hover:fill-pink-100',
        folderHoverStroke: 'group-hover:stroke-pink-300',
    },
};
